#source 'https://mirror.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'RxSwift', '5.0.1'
    pod 'RxCocoa', '5.0.1'
    pod 'Moya/RxSwift', '~> 14.0.0-beta.5'
    pod 'SwiftLint'
    pod 'HandyJSON', '~> 5.0.0-beta'
    pod 'Kingfisher'
end

target 'LLmyApp' do
	shared_pods
end
